# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/193L7Tvm91_naMssTN9Ate4tLVA8mtaSi
"""

# ========================================
# ✅ ФИНАЛЬНЫЙ ИСПРАВЛЕННЫЙ код для Colab
# Без SpeechT5 конфликта + стабильные версии
# ========================================

# 🔧 ЧИСТАЯ установка (без конфликтов)
!pip uninstall -y transformers huggingface-hub torch torchvision torchaudio accelerate
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
!pip install transformers==4.44.2 huggingface-hub==0.25.1 accelerate sentencepiece protobuf pillow
!pip install streamlit==1.38.0 pyngrok

# Проверка версий
import transformers
print(f"✅ Transformers: {transformers.__version__}")

# Импорты (без pipeline для избежания SpeechT5)
import io
import streamlit as st
import torch
from transformers import AutoProcessor, AutoModelForVision2Seq
from PIL import Image
from pyngrok import ngrok
import subprocess
import threading
import time
import os

print("✅ Импорты прошли успешно!")

# ========================================
# app.py - СТАБИЛЬНАЯ версия
# ========================================
app_code = '''
import io
import streamlit as st
import torch
from transformers import AutoProcessor, AutoModelForVision2Seq
from PIL import Image

# Ручная функция перевода (без pipeline)
@st.cache_resource
def load_translator_model():
    # Простой переводчик en-ru (локальный)
    from transformers import MarianMTModel, MarianTokenizer
    model_name = "Helsinki-NLP/opus-mt-en-ru"
    tokenizer = MarianTokenizer.from_pretrained(model_name)
    model = MarianMTModel.from_pretrained(model_name)
    return tokenizer, model

def translate_text(tokenizer, model, text):
    inputs = tokenizer(text, return_tensors="pt", padding=True, truncation=True)
    translated = model.generate(**inputs, max_length=512)
    return tokenizer.decode(translated[0], skip_special_tokens=True)

@st.cache_resource
def load_ocr_model():
    model_id = "microsoft/trocr-large-printed"  # ✅ Стабильная альтернатива!
    processor = AutoProcessor.from_pretrained(model_id, trust_remote_code=False)
    model = AutoModelForVision2Seq.from_pretrained(
        model_id,
        torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32,
        device_map="auto"
    )
    return processor, model

def load_image():
    uploaded_file = st.file_uploader(
        "📁 **Загрузите изображение**",
        type=['png', 'jpg', 'jpeg', 'webp']
    )
    if uploaded_file is not None:
        image_data = uploaded_file.getvalue()
        image = Image.open(io.BytesIO(image_data)).convert("RGB")
        st.image(image, caption="Загруженное изображение", use_column_width=True)
        return image
    return None

# UI
st.set_page_config(page_title="OCR Colab", page_icon="🔍", layout="wide")
st.title("🔍 **OCR + Перевод** (TrOCR Edition)")
st.markdown("### Английский текст → Русский 🇬🇧➡️🇷🇺")

with st.sidebar:
    st.header("ℹ️ Инфо")
    if torch.cuda.is_available():
        st.success(f"✅ GPU: {torch.cuda.get_device_name(0)}")
    else:
        st.warning("⚠️ CPU")

# Загрузка моделей
progress_bar = st.progress(0)
status_text = st.empty()

status_text.text("📥 Загрузка OCR...")
ocr_processor, ocr_model = load_ocr_model()
progress_bar.progress(50)

status_text.text("📥 Загрузка переводчика...")
translator_tokenizer, translator_model = load_translator_model()
progress_bar.progress(100)
status_text.success("✅ Готово!")

img = load_image()

if st.button("🚀 **РАСПОЗНАТЬ + ПЕРЕВЕСТИ**", type="primary") and img is not None:
    with st.spinner("🔄 Обработка..."):
        # OCR
        pixel_values = ocr_processor(img, return_tensors="pt").pixel_values

        if torch.cuda.is_available():
            pixel_values = pixel_values.to("cuda")

        generated_ids = ocr_model.generate(pixel_values, max_length=128)
        english_text = ocr_processor.batch_decode(generated_ids, skip_special_tokens=True)[0]

    col1, col2 = st.columns(2)
    with col1:
        st.success("🇬🇧 **English:**")
        st.code(english_text)

    with col2:
        with st.spinner("🇷🇺 Перевод..."):
            russian_text = translate_text(translator_tokenizer, translator_model, english_text)
        st.success("🇷🇺 **Русский:**")
        st.code(russian_text)

with st.expander("📖 Инструкция"):
    st.markdown("""
    1. Загрузите **изображение с английским текстом**
    2. Нажмите кнопку
    3. Получите **OCR + перевод**!
    """)

st.caption("✅ TrOCR + MarianMT | Стабильно работает в Colab")
'''

# Сохранение и запуск
with open("app.py", "w") as f:
    f.write(app_code)

print("✅ app.py готов!")

def run_streamlit():
    os.system("streamlit run app.py --server.port 8501 --server.address 0.0.0.0 > /dev/null 2>&1")

streamlit_thread = threading.Thread(target=run_streamlit)
streamlit_thread.daemon = True
streamlit_thread.start()

time.sleep(3)
public_url = ngrok.connect(8501)
print("\n" + "="*70)
print("🎉 **ПРИЛОЖЕНИЕ РАБОТАЕТ!**")
print(f"🔗 {public_url}")
print("="*70)