# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/193L7Tvm91_naMssTN9Ate4tLVA8mtaSi
"""

# ========================================
# 🔥 ПРОСТОЙ РАБОЧИЙ код (1 ячейка = полное приложение)
# НЕТ Streamlit! Прямой запуск в Colab
# ========================================

# 🔧 Установка
!pip install -q torch torchvision transformers pillow accelerate sentencepiece protobuf

# Импорты
import torch
from transformers import TrOCRProcessor, VisionEncoderDecoderModel, MarianMTModel, MarianTokenizer
from PIL import Image
import io
from IPython.display import display, HTML, clear_output
import ipywidgets as widgets
from google.colab import files

print("✅ Готово! Загружайте изображение 👇")

# ========================================
# Загрузка моделей
# ========================================
print("📥 Загрузка моделей...")

processor = TrOCRProcessor.from_pretrained("microsoft/trocr-large-printed")
ocr_model = VisionEncoderDecoderModel.from_pretrained("microsoft/trocr-large-printed")

tokenizer_ru = MarianTokenizer.from_pretrained("Helsinki-NLP/opus-mt-en-ru")
model_ru = MarianMTModel.from_pretrained("Helsinki-NLP/opus-mt-en-ru")

if torch.cuda.is_available():
    ocr_model.to("cuda")
    model_ru.to("cuda")
    print("✅ GPU активирован")
else:
    print("⚠️ CPU режим")

print("✅ Модели готовы!")

# ========================================
# UI элементы
# ========================================
upload_widget = widgets.FileUpload(
    accept='image/*',
    multiple=False,
    description="📁 Изображение"
)

output_image = widgets.Output()
output_english = widgets.Output()
output_russian = widgets.Output()

btn_recognize = widgets.Button(
    description="🚀 РАСПОЗНАТЬ + ПЕРЕВЕСТИ",
    button_style="success",
    layout=widgets.Layout(width="300px")
)

# ========================================
# Функция распознавания
# ========================================
def recognize_and_translate(change):
    with output_image:
        clear_output()

    if len(upload_widget.value) > 0:
        # Изображение
        uploaded_file = list(upload_widget.value.values())[0]
        image = Image.open(io.BytesIO(uploaded_file['content'])).convert("RGB")

        with output_image:
            display(image)

        # OCR
        with output_english:
            clear_output()
            print("🔄 Распознаём...")
            pixel_values = processor(image, return_tensors="pt").pixel_values
            if torch.cuda.is_available():
                pixel_values = pixel_values.to("cuda")

            generated_ids = ocr_model.generate(pixel_values)
            english_text = processor.batch_decode(generated_ids, skip_special_tokens=True)[0]
            print("\n✅ **🇬🇧 English:**")
            print("="*50)
            print(english_text)
            print("="*50)

        # Перевод
        with output_russian:
            clear_output()
            print("🔄 Переводим...")
            inputs = tokenizer_ru(english_text, return_tensors="pt", padding=True)
            if torch.cuda.is_available():
                inputs = {k: v.to("cuda") for k, v in inputs.items()}

            translated = model_ru.generate(**inputs)
            russian_text = tokenizer_ru.decode(translated[0], skip_special_tokens=True)

            print("\n✅ **🇷🇺 Русский:**")
            print("="*50)
            print(russian_text)
            print("="*50)

btn_recognize.on_click(recognize_and_translate)

# ========================================
# ГЛАВНЫЙ ИНТЕРФЕЙС
# ========================================
display(HTML("""
<div style="background: linear-gradient(90deg, #667eea 0%, #764ba2 100%); padding: 20px; border-radius: 15px; color: white; text-align: center; margin-bottom: 20px;">
    <h1>🔍 OCR + Перевод</h1>
    <p>🇬🇧 Английский текст → 🇷🇺 Русский | TrOCR Pro</p>
</div>
"""))

display(widgets.VBox([
    widgets.HTML("<h3>📁 1. Загрузите изображение:</h3>"),
    upload_widget,
    widgets.HTML("<br>"),
    btn_recognize,
    widgets.HTML("<br><h3>📊 2. Результаты:</h3>"),

    widgets.HTML("<h4>Изображение:</h4>"),
    output_image,

    widgets.HBox([
        widgets.VBox([
            widgets.HTML("<h4>🇬🇧 English:</h4>"),
            output_english
        ]),
        widgets.VBox([
            widgets.HTML("<h4>🇷🇺 Русский:</h4>"),
            output_russian
        ])
    ])
]))

print("\n🎉 **ГОТОВО!**")
print("1. Нажмите 'Выберите файл' и загрузите изображение")
print("2. Нажмите 'РАСПОЗНАТЬ + ПЕРЕВЕСТИ'")
print("3. Получите результат мгновенно! 🚀")